BASE_URL = "https://service.mokaunited.com"
TEST_URL = "https://service.refmokaunited.com"
API_VERSION = "v1"
API_URL = f"{BASE_URL}"
PAYMENT_USER_POS = f"{API_URL}/PaymentUserPos"
CREATE_USER_POS_PAYMENT = f"{PAYMENT_USER_POS}/CreateUserPosPayment"