version: '3.8'

services:
  payment-server-stdio:
    build: .
    environment:
      - PROVIDER=moka
      - DEALER_CODE=${DEALER_CODE}
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - CUSTOMER_TYPE_ID=${CUSTOMER_TYPE_ID:-2}
      - TRANSPORT=stdio
    volumes:
      - ./logs:/app/logs
    profiles:
      - stdio

  payment-server-sse:
    build: .
    environment:
      - PROVIDER=moka
      - DEALER_CODE=${DEALER_CODE}
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - CUSTOMER_TYPE_ID=${CUSTOMER_TYPE_ID}
      - TRANSPORT=sse
      - HOST=0.0.0.0
      - PORT=8060
      - AUTH_TOKEN=${AUTH_TOKEN}
    ports:
      - "8060:8060"
    volumes:
      - ./logs:/app/logs
    profiles:
      - sse